/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.16).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package operation.quasar.api;

import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiParam;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
import operation.quasar.model.ApiError;
import operation.quasar.model.PositionResponse;
import operation.quasar.model.Satellites;
import operation.quasar.model.SatellitesRequestSplit;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import javax.validation.Valid;

@RequestMapping(value = "/v2")
public interface SateliteApi {


    @ApiOperation(value = "Metodo para consultar la distancia", nickname = "getPetById", response = PositionResponse.class, tags = {"topsecret_split",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "successful operationnnn", response = PositionResponse.class),
            @ApiResponse(code = 404, message = "Satelite not found", response = ApiError.class)})

    @GetMapping(value = "/topsecret_split/{name}")
    ResponseEntity<PositionResponse> topsecretSplitGet(@ApiParam(value = "ID of pet to return", required = true) @PathVariable("name") String name);


    @ApiOperation(value = "Agrego las distancia de los satelites", nickname = "Payload", notes = "", response = PositionResponse.class, tags = {"topsecret",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "successful operationnnn", response = PositionResponse.class),
            @ApiResponse(code = 404, message = "Satelite not found", response = ApiError.class)})

    @PostMapping(value = "/topsecret")
    ResponseEntity<PositionResponse> topsecret(@ApiParam(value = "object that needs to be added to the store", required = true)
                                               @Valid @RequestBody Satellites requestSatelites);


    @ApiOperation(value = "Agrego la distancia de un satelite", nickname = "Payload", notes = "", tags = {"topsecret_split",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "successful operationnnn", response = PositionResponse.class),
            @ApiResponse(code = 404, message = "Satelite not found", response = ApiError.class)})

    @PostMapping(value = "/topsecret_split/{name}")
    ResponseEntity<Void> topsecretSplit(@ApiParam(value = "Metodo que se usa para Agregor la distancia de un satelite", required = true)
                                        @PathVariable("name") String name, @Valid @RequestBody SatellitesRequestSplit satellitesRequestSplit);
}
